### ISSUE TITLE
fix: thread 'main' panicked at 'config could not be loaded' src/main.rs:215:14

### ISSUE THREAD

**Issue by tomassasovsky** [segler-alex/radiobrowser-api-rust#185]
I'm trying to get this to run in a Docker Compose file:

```
version: '3.9'
services:
  radio_garden:
    build:
      context: .
      args:
          dart_entryfile: radio_garden_development.dart
    container_name: radio_garden
    expose:
      - 8081
    env_file:
     - .env/.env.development
    links:
      - lavalink
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink
    restart: always
    expose:
      - 2333
    volumes:
     - ./lavalink.yml:/opt/Lavalink/application.yml

  dbserver:
    image: mariadb
    container_name: dbserver
    environment:
      MYSQL_DATABASE: radio
      MYSQL_USER: radiouser
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"
    networks:
      - rbnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  radiobrowserapi:
    image: segleralex/radiobrowser-api-rust:latest
    container_name: radiobrowserapi
    environment:
      DATABASE_URL: mysql://radiouser:password@dbserver/radio
      HOST: "0.0.0.0"
    ports:
      - "8080:8080"
    networks:
      - rbnet
    command: radiobrowser-api-rust -vvv

networks:
  rbnet:
```

This is the error I get:

```
2023-03-18 21:39:26 thread 'main' panicked at 'config could not be loaded', src/main.rs:215:14
2023-03-18 21:39:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
